const projects=[
{title:"Multi-Agent Incident Commander",type:"Generative AI / Hackathon",desc:"Incident-response copilot using RAG, LLMs and AI agents to correlate alerts, logs and deployment events.",tags:["AI Agents","RAG","LLM"]},
{title:"Spring Boot CI/CD Demo",type:"DevOps",desc:"Spring Boot application demonstrating automated testing and delivery with Jenkins, GitHub Actions and Docker.",tags:["Java","Jenkins","Docker"]},
{title:"Network Performance Monitor",type:"Computer Networks",desc:"Flask dashboard that monitors latency and packet loss and classifies network health.",tags:["Python","Flask","Networking"]},
{title:"Smart Queue Prediction App",type:"Flutter",desc:"Mobile queue-management concept with separate Home, Staff and Admin experiences.",tags:["Flutter","Dart","UI"]},
{title:"Self-Healing Web Application",type:"DevOps",desc:"Reliability-focused project exploring health checks, containers and automatic application recovery.",tags:["Docker","CI/CD","Monitoring"]}];
const skills=["Java","Python","C","HTML","CSS","JavaScript","React","Next.js","Flutter","Git & GitHub","Docker","Jenkins","AI / LLM","RAG"];
const achievements=["Pinnacle Labs Internship","GSSoC","AWS Cloud Event","Microsoft Azure + Copilot Workshop","Samsung Galaxy Quiz","LeetCode 50-Day Streak","Hackathon Participation"];
export default function Home(){return <main>
<header className="nav"><a className="logo" href="#">VK<span>.</span></a><nav><a href="#about">About</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav><a className="navBtn" href="https://github.com/vamshi1808" target="_blank">GitHub ↗</a></header>
<section className="hero"><div className="eyebrow">CSE STUDENT · DEVELOPER · BUILDER</div><h1>Building useful software<br/><span>with AI, DevOps & code.</span></h1><p className="heroText">I’m Vamshi Krishna, a third-year Computer Science Engineering student focused on practical software projects, problem solving and modern development technologies.</p><div className="actions"><a className="primary" href="#projects">View my work ↓</a><a className="secondary" href="https://linkedin.com/in/vamshi-krishna-734900326" target="_blank">LinkedIn ↗</a></div><div className="stats"><div><strong>8.1</strong><small>CGPA</small></div><div><strong>2028</strong><small>GRADUATION</small></div><div><strong>5+</strong><small>PROJECTS</small></div></div></section>
<section id="about" className="section about"><div className="label">01 / ABOUT</div><div><h2>Learning by building.</h2><p>I’m pursuing B.Tech in Computer Science Engineering at CMR Technical Campus. I enjoy turning ideas into working applications and exploring AI, web development, cloud and DevOps.</p><p>I’m focused on improving my coding fundamentals, building stronger projects and becoming a dependable software developer.</p><div className="miniActions"><a href="https://github.com/vamshi1808" target="_blank">GitHub Profile ↗</a><a href="https://linkedin.com/in/vamshi-krishna-734900326" target="_blank">LinkedIn ↗</a></div></div></section>
<section id="skills" className="section"><div className="label">02 / SKILLS</div><div><h2>Tools I work with.</h2><div className="skillGrid">{skills.map(s=><div className="skill" key={s}>{s}</div>)}</div></div></section>
<section id="projects" className="section projects"><div className="label">03 / PROJECTS</div><div><h2>Things I’ve built.</h2><div className="projectGrid">{projects.map((p,i)=><article className="card" key={p.title}><div className="cardTop"><span>0{i+1}</span><span>{p.type}</span></div><h3>{p.title}</h3><p>{p.desc}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><a className="projectLink" href="https://github.com/vamshi1808" target="_blank">View on GitHub ↗</a></article>)}</div></div></section>
<section id="experience" className="section"><div className="label">04 / EXPERIENCE</div><div className="timeline"><div className="timelineItem"><span>2026</span><div><h3>Pinnacle Labs — Internship</h3><p>Completed an internship experience with practical development exposure.</p></div></div><div className="timelineItem"><span>2026</span><div><h3>Hackathons & Technical Events</h3><p>Participated in hackathons, cloud events, workshops and coding activities.</p></div></div><div className="timelineItem"><span>2024—28</span><div><h3>B.Tech Computer Science Engineering</h3><p>CMR Technical Campus · Expected graduation 2028.</p></div></div></div></section>
<section className="section achievements"><div className="label">05 / ACHIEVEMENTS</div><div><h2>Beyond the classroom.</h2><div className="achievementGrid">{achievements.map((a,i)=><div className="achievement" key={a}><span>0{i+1}</span><strong>{a}</strong></div>)}</div></div></section>
<section id="contact" className="contact"><div className="label">06 / CONTACT</div><h2>Let’s build something.</h2><p>Open to internships, projects, learning opportunities and meaningful collaborations.</p><div className="actions"><a className="primary" href="https://github.com/vamshi1808" target="_blank">GitHub ↗</a><a className="secondary" href="https://linkedin.com/in/vamshi-krishna-734900326" target="_blank">LinkedIn ↗</a></div></section>
<footer><span>© 2026 Vamshi Krishna</span><span>Built with Next.js · CMR Technical Campus</span></footer></main>}