const projects=[
{title:"Multi-Agent Incident Commander",type:"Generative AI / Hackathon",desc:"Incident-response copilot using RAG, LLMs and AI agents to correlate alerts, logs and deployment events.",tags:["AI Agents","RAG","LLM"]},
{title:"Spring Boot CI/CD Demo",type:"DevOps",desc:"Spring Boot application demonstrating automated testing and delivery with Jenkins, GitHub Actions and Docker.",tags:["Java","Jenkins","Docker"]},
{title:"Network Performance Monitor",type:"Computer Networks",desc:"Flask dashboard that monitors latency and packet loss and classifies network health.",tags:["Python","Flask","Networking"]},
{title:"Smart Queue Prediction App",type:"Flutter",desc:"Mobile queue-management concept with separate Home, Staff and Admin experiences.",tags:["Flutter","Dart","UI"]},
{title:"Self-Healing Web Application",type:"DevOps",desc:"Reliability-focused project exploring health checks, containers and automatic application recovery.",tags:["Docker","CI/CD","Monitoring"]}];
const skills=["Java","Python","C","HTML","CSS","JavaScript","React","Next.js","Flutter","Git & GitHub","Docker","Jenkins","AI / LLM","RAG"];
const achievements=["Pinnacle Labs Internship","GSSoC","AWS Cloud Event","Microsoft Azure + Copilot Workshop","Samsung Galaxy Quiz","LeetCode 50-Day Streak","Hackathon Participation"];
const nav=[["home","Home"],["about","About"],["skills","Skills"],["projects","Projects"],["experience","Experience"],["contact","Contact"]];
export default function Home(){return <main className="slideSite">
<header className="nav"><a className="logo" href="#home">VK<span>.</span></a><nav>{nav.map(([id,label])=><a key={id} href={"#"+id}>{label}</a>)}</nav><a className="navBtn" href="https://github.com/vamshi1808" target="_blank">GitHub ↗</a></header>
<div className="slideProgress"><span/><span/><span/><span/><span/><span/></div>
<section id="home" className="slide hero"><div className="heroGlow glowOne"/><div className="heroGlow glowTwo"/><div className="slideInner heroInner"><div className="eyebrow"><span className="statusDot"/> CSE STUDENT · DEVELOPER · BUILDER</div><h1>Building useful software<br/><span>with AI, DevOps & code.</span></h1><p className="heroText">I’m Vamshi Krishna, a third-year Computer Science Engineering student focused on practical software projects, problem solving and modern development technologies.</p><div className="actions"><a className="primary" href="#projects">Explore Projects <span>→</span></a><a className="secondary" href="https://linkedin.com/in/vamshi-krishna-734900326" target="_blank">LinkedIn ↗</a></div><div className="stats"><div><strong>8.1</strong><small>CGPA</small></div><div><strong>2028</strong><small>GRADUATION</small></div><div><strong>5+</strong><small>PROJECTS</small></div><div className="available"><span/> Available for opportunities</div></div></div></section>
<section id="about" className="slide"><div className="slideInner split"><div className="label">01 / ABOUT</div><div className="windowCard"><div className="windowTop"><i/><i/><i/><span>about.vk</span></div><h2>Learning by <em>building.</em></h2><p>I’m pursuing B.Tech in Computer Science Engineering at CMR Technical Campus. I enjoy turning ideas into working applications and exploring AI, web development, cloud and DevOps.</p><p>I’m focused on improving my coding fundamentals, building stronger projects and becoming a dependable software developer.</p><div className="miniActions"><a href="https://github.com/vamshi1808" target="_blank">GitHub Profile ↗</a><a href="https://linkedin.com/in/vamshi-krishna-734900326" target="_blank">LinkedIn ↗</a></div></div></div></section>
<section id="skills" className="slide"><div className="slideInner split"><div className="label">02 / SKILLS</div><div><h2>Tools I <em>work with.</em></h2><div className="skillGrid">{skills.map((s,i)=><div className="skill" key={s}><span>{String(i+1).padStart(2,"0")}</span>{s}</div>)}</div></div></div></section>
<section id="projects" className="slide"><div className="slideInner split"><div className="label">03 / PROJECTS</div><div><h2>Things I’ve <em>built.</em></h2><div className="projectGrid">{projects.map((p,i)=><article className="card" key={p.title}><div className="cardTop"><span>PROJECT 0{i+1}</span><span>{p.type}</span></div><div className="cardIcon">{["✦","⌘","⌁","◈","↻"][i]}</div><h3>{p.title}</h3><p>{p.desc}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><a className="projectLink" href="https://github.com/vamshi1808" target="_blank">View on GitHub ↗</a></article>)}</div></div></div></section>
<section id="experience" className="slide"><div className="slideInner split"><div className="label">04 / EXPERIENCE</div><div className="timelineWindow"><div className="timelineItem"><span>2026</span><div><h3>Pinnacle Labs — Internship</h3><p>Completed an internship experience with practical development exposure.</p></div></div><div className="timelineItem"><span>2026</span><div><h3>Hackathons & Technical Events</h3><p>Participated in hackathons, cloud events, workshops and coding activities.</p></div></div><div className="timelineItem"><span>2024—28</span><div><h3>B.Tech Computer Science Engineering</h3><p>CMR Technical Campus · Expected graduation 2028.</p></div></div></div></div></section>
<section id="achievements" className="slide"><div className="slideInner split"><div className="label">05 / ACHIEVEMENTS</div><div><h2>Beyond the <em>classroom.</em></h2><div className="achievementGrid">{achievements.map((a,i)=><div className="achievement" key={a}><span>0{i+1}</span><strong>{a}</strong><b>↗</b></div>)}</div></div></div></section>
<section id="contact" className="slide contactSlide"><div className="contactGlow"/><div className="slideInner contactInner"><div className="label">06 / CONTACT</div><h2>Let’s build <em>something.</em></h2><p>Open to internships, projects, learning opportunities and meaningful collaborations.</p><div className="actions"><a className="primary" href="https://github.com/vamshi1808" target="_blank">GitHub ↗</a><a className="secondary" href="https://linkedin.com/in/vamshi-krishna-734900326" target="_blank">LinkedIn ↗</a></div></div></section>
<footer><span>© 2026 Vamshi Krishna</span><span>Built with Next.js · CMR Technical Campus</span></footer></main>}